<section class="copy-generic">
	<div class="content">
		<div class="inner-content">
			<div class="copy-container">
				<h1 class="center">Stacey H.S. Hipsman <span class="team-title blue block"><em>VP of Human Resources</em></span></h1>
				<p>Stacey H.S. Hipsman joined Butterfly Effects, LLC in 2018 as Vice-President of Human Resources.  Previously, she was Director for all U.S. based assets for Silva International Investments, which included investments across a range of companies across media, sports, entertainment, art, digital, and real estate in a full portfolio.  Additionally, she has provided service to executives in the automotive and motorcycle sectors and has more than 20 years of experience in the public and private sector including serving as the Human Resources Director/Chief Negotiator for the State of Florida/DCF and municipalities as well as handling significant clients and employment cases, she brings high level executive expertise and is nationally recognized for her talent in labor and employment issues.  Ms. Hipsman has successfully resolved numerous class actions both for plaintiffs and employers including United Technologies (Pratt & Whitney); Nextera (FPL); and Forman Foundation/Broward Port.  She has represented numerous clients in the Federal courts (including more than 80- 11th Circuit Court of Appeals cases, dozens of wage & hour administrative hearings; and 12 successful 1983 Civil Rights actions against municipalities from Key West to Orlando) including Lloyd’s of London, Lawless Harley-Davidson, USA; Beth Ann Faragher vs City of Boca Raton (Landmark Employment Law Case); Debra Jo Schneider vs. Don Browne, NBC, written dozens of Amicus Briefs in the Supreme Court including on behalf of the English Language for the Cuban American Foundation; participated in drafting of the Americans with Disabilities Act and revisions, Amendments to the FLSA and the revisions to Florida Statutes Chapters 447/39 and 440 . Additionally, Ms. Hipsman was a  representative on behalf of  the Mayors off the United States on the Affordable Care Act with the then Secretary of Health and the President.</p>
				<p>Ms. Hipsman has served on the Advisory Board of United Healthcare, Sylvester Comprehensive Center-Friends of Sylvester.  She actively volunteers as Moot Court Judge for the University of Miami Law School and is recipient of 3 Governor’s Awards for the Repatriation of 7500 Haitian American Children; the Modernization of the Economic Services Program; and architect of the revisions to Civil Service statutes; known as “Service First” legislation. Also, past awards include recipient of the American Legion Award and is author of both the State of Florida’s Primer on Workers’ Compensation and Grievance Procedures in State Government with Methods for Discipline and Dispute Resolution.</p>
				<p>Her education includes a Bachelor's Degree from the George Washington University and a J.D. from the University of Miami.</p>
			</div>
		</div>
	</div>
</section>